username: dsartiom@gmail.com
password: test.app
imap_url: imap.gmail.com
download_folder: C:/Users/david/Desktop/PyCodes/github/emailCollector/downloads/
email_sender: ticket_digital@mail.mercadona.com